services:
  hospital_db:
    image: postgres:13
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
    ports:
      - "5433:5432"
    volumes:
      - ./hospital-data:/var/lib/postgresql/data

  hospital_app:
    build: .
    depends_on:
      - hospital_db
    environment:
      DB_HOST: hospital_db
      DB_USER: hospital_user
      DB_PASSWORD: hospital_password
      DB_NAME: hospital_db
    ports:
      - "8080:8080"
    networks:
      - hospital_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hospital_app
    networks:
      - hospital_network

networks:
  hospital_network:
