version: '3.8'

services:
  hospital_db:
    image: postgres:13
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
    ports:
      - "5433:5432"
    volumes:
      - ./hospital-data:/var/lib/postgresql/data
